# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LadderGameSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LadderGameSwiftUI

  target 'LadderGameSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LadderGameSwiftUIUITests' do
    # Pods for testing
  end

end
